### ISSUE TITLE
using bmd on a model fitted with curveid

### ISSUE THREAD

**Issue by vahidnassiri** [DoseResponse/bmd#1]
In `drm` we have the option to use `curveid` to fit multiple dose-response curves, using `ED` on such a fitted object works fine, but I wonder how we can use `bmd` to find the benchmark dose for each curve separately.

**Comment by SigneMJensen** [comment]
This is not possible yet but is thought to be part of a future update

**Comment by JensBaalkilde** [comment]
This is now possible in the newest version of the package. (2.4.1)
