### ISSUE TITLE
Cannot estimate BMD with interval = "delta" (object$fct$derivx is NULL)

### ISSUE THREAD

**Issue by periklis91** [DoseResponse/bmd#26]
BMD cannot be estimated through the bmd function for several drc models, e.g. for EXD.3(), when using the default "interval" value, i.e. "delta". In particular, line 60 of the BMD.R script :
 >dBmdVal <- EDeval[[2]] + bmrScaledList$dBmrScaled[,1] / object$fct$derivx(bmdVal, t(parmMat))[1] 

returns:

> Error: attempt to apply non-function for several models. 

I am using  bmd_2.6.2   and  drc_3.0-1. I found that this line does not work for many models, because these models do not have a 'derivx' property.

**Comment by JensBaalkilde** [comment]
Hi

Thank you bringing this to our attention. I have just updated the bmd package adressing your issue. There is a newer version of the drc package (3.2-0) available on GitHub, which we generally recommend, in which the missing derivatives of the dose-response curves are implemented. However, for the sake of the convenience of you and other users with the CRAN version of the drc package installed, the newest version of the bmd package now defines the required derivatives of the dose-response curves without the need to update the drc package. 

The interval and type options have also been clarified on the help page for the bmdMA function. 

Once again, thanks for bringing this to our attention. Make sure to reach out to us again, if you still experience problems with the bmd package.

- Jens Riis Baalkilde
